@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status') == 'two-factor-authentication-enabled')
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ __('Please finish configuring two factor authentication in this page.') }}
                            <a href="{{ route('twoFactorSettings') }}">Two Factor Settings</a>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @elseif (session('status') == 'two-factor-authentication-disabled')
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ __('Two factor authentication disabled successfully.') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif

                    <div class="text-bold mb-3">{{ __('You are logged in!') }}</div>

                        <h2>How to Enable Two-Factor Authentication?</h2>
                        <ol>
                            <li>Activate Two-Factor Authentication by clicking the "Enable 2FA" button.</li>
                            <li>Confirm your password using your app password.</li>
                            <li>Click the "Two-Factor Settings" link.</li>
                            <li>Scan the QR code using your authenticator app (Google Authenticator, etc).</li>
                            <li>Enter the authentication code generated by the app (Google Authenticator, etc).</li>
                            <li>Click the "Confirm 2FA" button.</li>
                            <li>Save the recovery code provided (if any).</li>
                            <li>Finish: Two-Factor Authentication is now enabled for your account.</li>
                        </ol>

                        <h2>Login with Two-Factor Authentication</h2>
                        <ol>
                            <li>Enter your username and password on the login page.</li>
                            <li>You will be prompted to enter the authentication code (Two-Factor Challenge Code or Recovery Code).</li>
                            <li>Open your authenticator app and retrieve the authentication code (if you are logging in with Two-Factor Code such as Google Authenticator, etc).</li>
                            <li>Enter the authentication code in the provided field on the login page.</li>
                            <li>Click the "Confirm Code" button.</li>
                            <li>If the authentication code is correct, you will be logged in to your dashboard account.</li>
                            <li>If the authentication code is incorrect, you may retry entering the code or use a recovery code.</li>
                            <li>Once logged in, you will have access to your account as usual.</li>
                        </ol>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
